[workspace]
resolver="2"

exclude = [
    "orderbook",
    "authentication",
    "coinbase",
    "library",
    "iot-retrieval-svc",
    "ritual",
    "minigrep",
    "paper-exchange",
    "sandbox-grin",
]

members = ["webrtc", "graphql-exchange"]