[workspace]

members = [
    "actix-web",
    "exchange",
    "iot-one",
    "minigrep",
    "prophet",
    "sandbox-bevy",
    "sandbox-exchange",
    "sandbox-smart-pointers",
    "sandbox-threading",
    "sandbox-one",
    "sandbox-oop",
    "sandbox-two",
    "sandbox-three",
    "sandbox-twenty",
    "tarot"
]