[workspace]
resolver = "2"

exclude = [
    "auth-service",
    "authentication",
    "library",
    "iot-retrieval-svc",
    "ritual",
    "minigrep",
    "paper-exchange",
    "sandbox-grin",
]

members = [
    "graphql-backend",
]
