[package]
name = "sandbox-exchange"
version = "0.1.0"
edition = "2018"

[lib]
name = "sandbox_exchange"
path = "src/lib.rs"

[dependencies]
exchange = { path = "../exchange" }
actix-web = "4"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
